import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

interface DecisionEntry {
  content: string;
  tags: string[];
  date: string;
}

function runBrvCommand(command: string): string {
  try {
    return execSync(`brv ${command}`, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
  } catch (error: any) {
    return error.stdout?.toString() || '';
  }
}

function parseEntries(output: string): DecisionEntry[] {
  const entries: DecisionEntry[] = [];
  const lines = output.split('\n').filter(l => l.trim());

  for (const line of lines) {
    const tags = (line.match(/#\w+/g)) || [];
    if (line.length > 10) {
      entries.push({
        content: line.replace(/#\w+/g, '').trim(),
        tags,
        date: new Date().toISOString().split('T')[0]
      });
    }
  }
  return entries;
}

function formatWeeklySummary(entries: DecisionEntry[], weekStart: string, weekEnd: string): string {
  const decisions = entries.filter(e => e.tags.includes('#decision'));
  const architecture = entries.filter(e => e.tags.includes('#architecture'));
  const direction = entries.filter(e => e.tags.includes('#product') || e.tags.includes('#direction'));
  const other = entries.filter(e => !e.tags.some(t => ['#decision', '#architecture', '#product', '#direction'].includes(t)));

  let md = `---\n`;
  md += `date: ${weekStart} — ${weekEnd}\n`;
  md += `tags: weekly-summary\n`;
  md += `---\n\n`;
  md += `# Weekly Summary: ${weekStart} — ${weekEnd}\n\n`;

  if (decisions.length > 0) {
    md += `## Key Decisions\n\n`;
    for (const d of decisions) {
      md += `- ${d.content}\n`;
    }
    md += `\n`;
  }

  if (architecture.length > 0) {
    md += `## Architecture Changes\n\n`;
    for (const a of architecture) {
      md += `- ${a.content}\n`;
    }
    md += `\n`;
  }

  if (direction.length > 0) {
    md += `## Product Direction\n\n`;
    for (const d of direction) {
      md += `- ${d.content}\n`;
    }
    md += `\n`;
  }

  if (other.length > 0) {
    md += `## Other Notable Items\n\n`;
    for (const o of other.slice(0, 10)) {
      md += `- ${o.content}\n`;
    }
    md += `\n`;
  }

  if (entries.length === 0) {
    md += `_No notable items this week._\n\n`;
  }

  md += `---\n`;
  md += `*Auto-generated by memory maintenance job*\n`;

  return md;
}

export async function syncObsidian(): Promise<void> {
  // Determine obsidian vault path
  const workspaceDir = process.env.WORKSPACE_DIR || process.cwd();
  const obsidianVault = path.resolve(workspaceDir, '../../obsidian');

  // Fallback: if no obsidian vault exists, write to a local summaries dir
  const summariesDir = fs.existsSync(obsidianVault)
    ? path.join(obsidianVault, 'weekly-summaries')
    : path.resolve(process.cwd(), 'reports/weekly-summaries');

  if (!fs.existsSync(summariesDir)) {
    fs.mkdirSync(summariesDir, { recursive: true });
  }

  // Fetch weekly decisions from ByteRover
  const decisionsOutput = runBrvCommand('search "#decision" --since "7 days ago"');
  const architectureOutput = runBrvCommand('search "#architecture" --since "7 days ago"');
  const productOutput = runBrvCommand('search "#product OR #direction" --since "7 days ago"');

  const allEntries: DecisionEntry[] = [
    ...parseEntries(decisionsOutput),
    ...parseEntries(architectureOutput),
    ...parseEntries(productOutput)
  ];

  // Deduplicate by content
  const seen = new Set<string>();
  const uniqueEntries = allEntries.filter(e => {
    const key = e.content.toLowerCase().slice(0, 80);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Compute week range
  const now = new Date();
  const dayOfWeek = now.getDay(); // 0 = Sunday
  const weekEnd = new Date(now);
  const weekStart = new Date(now);
  weekStart.setDate(now.getDate() - dayOfWeek);

  const startStr = weekStart.toISOString().split('T')[0];
  const endStr = weekEnd.toISOString().split('T')[0];

  const mdContent = formatWeeklySummary(uniqueEntries, startStr, endStr);
  const filename = `${startStr}.md`;
  const filePath = path.join(summariesDir, filename);

  fs.writeFileSync(filePath, mdContent);

  console.log(`Obsidian sync complete: ${filePath}`);
  console.log(`Entries written: ${uniqueEntries.length}`);
}

// Run if executed directly
if (require.main === module) {
  syncObsidian().catch(console.error);
}
